name: Build Android APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v2

      - name: Python ortamını kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Buildozer ve bağımlılıkları kur
        run: |
          sudo apt update
          sudo apt install -y zip unzip build-essential git openjdk-17-jdk python3-pip \
            libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev \
            libncurses5 libstdc++6 libjpeg-dev libandroid-tools adb
          pip install --upgrade pip
          pip install cython virtualenv
          pip install buildozer

      - name: APK derle (debug)
        run: |
          buildozer android debug

      - name: APK'yi yükle (indirilebilir hale getir)
        uses: actions/upload-artifact@v2
        with:
          name: AI-Root-Assistant-APK
          path: bin/*.apk
